-- If set A = {H  I  J  K  L  M} and set B = {L  M  N  O  P}, what set is generated by the [A union B] operation?
-- ANSWER: SET { H I J K L M N O P }

-- PROBLEM 2
-- ANSWER: SET { H I J K L M L M N O P }

-- PROBLEM 3
SELECT last_update
FROM actor
UNION
SELECT last_update
FROM film
UNION
SELECT last_update
FROM category;

-- PROBLEM 4
SELECT last_update
FROM actor
UNION ALL
SELECT last_update
FROM film
UNION ALL
SELECT last_update
FROM category;

-- PROBLEM 5
SELECT * FROM (SELECT first_name, last_name
				FROM actor
				UNION
				SELECT first_name, last_name
				FROM customer) A
WHERE A.last_name LIKE "L%";

-- PROBLEM 6
SELECT * FROM (SELECT first_name, last_name
				FROM actor
				UNION
				SELECT first_name, last_name
				FROM customer) A
WHERE A.last_name LIKE "L%"
ORDER BY A.last_name;